/**
 * Alternative seed script — inserts the 60 seed sites via Supabase client
 * instead of SQL Editor. Use this if the SQL Editor isn't working.
 *
 * Run with: npx tsx scripts/seed-sites.ts
 */

import dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });
import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'fs';
import { join } from 'path';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const sites = [
  { url: 'https://huggingface.co', title: 'Hugging Face', description: 'The AI community building the future — models, datasets, and ML apps all in one place.', categories: ['technology','ai-ml'], tags: ['machine-learning','models','nlp','open-source','community'], content_type: 'community', quality_score: 95, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://roadmap.sh', title: 'roadmap.sh', description: 'Community-driven developer roadmaps, guides, and learning paths for every tech stack.', categories: ['technology','developer-tools'], tags: ['learning','roadmap','career','programming','guides'], content_type: 'resource', quality_score: 92, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://github.com/sindresorhus/awesome', title: 'Awesome Lists', description: "The original curated list of awesome lists — a meta-collection of the internet's best resources.", categories: ['technology','open-source'], tags: ['curated','lists','resources','github','developer'], content_type: 'resource', quality_score: 90, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://tldr.tech', title: 'TLDR Newsletter', description: 'Byte-sized daily newsletter covering the most interesting stories in startups, tech, and programming.', categories: ['technology','ai-ml'], tags: ['newsletter','daily','tech-news','startups','programming'], content_type: 'blog', quality_score: 88, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.awwwards.com', title: 'Awwwards', description: 'Recognizing the talent and effort of the best web designers, developers, and agencies.', categories: ['design-creative','web-design'], tags: ['awards','inspiration','web-design','showcase','creativity'], content_type: 'community', quality_score: 94, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://typewolf.com', title: 'Typewolf', description: 'Helping designers choose the perfect font combination — real-world typography inspiration.', categories: ['design-creative','typography-fonts'], tags: ['typography','fonts','design','inspiration','pairings'], content_type: 'resource', quality_score: 91, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.refactoringui.com', title: 'Refactoring UI', description: 'Learn UI design with specific tactics from the creators of Tailwind CSS.', categories: ['design-creative','ui-ux'], tags: ['ui-design','tailwind','tips','practical','visual'], content_type: 'resource', quality_score: 93, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://dribbble.com', title: 'Dribbble', description: "Discover the world's top designers & creatives — the leading destination for design portfolios.", categories: ['design-creative','design-inspiration'], tags: ['portfolios','showcase','community','hiring','inspiration'], content_type: 'community', quality_score: 89, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.indiehackers.com', title: 'Indie Hackers', description: 'A community of founders sharing the revenue numbers and strategies behind their businesses.', categories: ['startups-business','indie-hacking-solopreneurs'], tags: ['founders','revenue','community','bootstrapping','transparency'], content_type: 'community', quality_score: 93, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.acquired.fm', title: 'Acquired Podcast', description: 'Deep dives into the greatest technology acquisitions and IPOs of all time.', categories: ['startups-business','venture-fundraising'], tags: ['podcast','acquisitions','business-history','analysis','tech'], content_type: 'resource', quality_score: 92, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.levels.fyi', title: 'Levels.fyi', description: 'Compare verified compensation data across tech companies — salaries, stock, and bonuses.', categories: ['startups-business','analytics-data'], tags: ['salary','compensation','tech-companies','data','transparency'], content_type: 'tool', quality_score: 90, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://waitbutwhy.com', title: 'Wait But Why', description: "Tim Urban's long-form explorations of science, philosophy, and everything that matters.", categories: ['science-nature','psychology-behavior'], tags: ['longform','philosophy','science','illustrated','thinking'], content_type: 'blog', quality_score: 96, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.quantamagazine.org', title: 'Quanta Magazine', description: 'Illuminating mathematics, physics, biology, and computer science research for curious minds.', categories: ['science-nature','math-logic'], tags: ['research','mathematics','physics','biology','journalism'], content_type: 'blog', quality_score: 95, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://apod.nasa.gov', title: 'NASA Astronomy Picture of the Day', description: "A different astronomy image or photograph every day, with a professional astronomer's explanation.", categories: ['science-nature','space-astronomy'], tags: ['space','photos','daily','nasa','astronomy'], content_type: 'resource', quality_score: 94, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.booooooom.com', title: 'Booooooom', description: 'An independent art platform founded by artist Jeff Hamada — art, film, music, and photography.', categories: ['arts-expression','visual-art-illustration'], tags: ['art','photography','film','independent','curation'], content_type: 'blog', quality_score: 92, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.brainpickings.org', title: 'The Marginalian', description: "Maria Popova's labor of love exploring what it means to live a meaningful life through books and art.", categories: ['arts-expression','writing-literature'], tags: ['books','philosophy','art','culture','longform'], content_type: 'blog', quality_score: 95, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://everynoise.com', title: 'Every Noise at Once', description: 'An algorithmically-generated, readability-adjusted scatter-plot of every music genre.', categories: ['arts-expression','music-audio'], tags: ['music','genres','visualization','discovery','interactive'], content_type: 'tool', quality_score: 91, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://aeon.co', title: 'Aeon', description: 'A digital magazine of ideas, philosophy, and culture — long essays from world-class thinkers.', categories: ['culture-ideas','philosophy-ethics'], tags: ['essays','philosophy','culture','thinking','longform'], content_type: 'blog', quality_score: 94, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.are.na', title: 'Are.na', description: 'A platform for connecting ideas and building knowledge — a visual thinking tool for the curious.', categories: ['culture-ideas','internet-culture'], tags: ['curation','visual-thinking','knowledge','bookmarking','creative'], content_type: 'tool', quality_score: 91, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://longnow.org', title: 'The Long Now Foundation', description: 'Fostering long-term thinking and responsibility in the framework of the next 10,000 years.', categories: ['culture-ideas','futurism-speculation'], tags: ['long-term','thinking','civilization','time','responsibility'], content_type: 'resource', quality_score: 90, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.seriouseats.com', title: 'Serious Eats', description: 'Authoritative, tested, and trustworthy recipes and food science from J. Kenji Lopez-Alt and team.', categories: ['lifestyle-wellness','food-cooking'], tags: ['recipes','food-science','cooking','tested','technique'], content_type: 'resource', quality_score: 93, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.atlasobscura.com', title: 'Atlas Obscura', description: "The definitive guide to the world's hidden wonders — curious and unusual travel destinations.", categories: ['lifestyle-wellness','travel-places'], tags: ['travel','unusual','hidden','wonders','exploration'], content_type: 'resource', quality_score: 94, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.theminimalists.com', title: 'The Minimalists', description: 'Helping millions live meaningful lives with less through writing, podcasts, and documentary films.', categories: ['lifestyle-wellness','sustainability'], tags: ['minimalism','intentional-living','podcast','simplicity','mindfulness'], content_type: 'blog', quality_score: 87, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://itch.io', title: 'itch.io', description: 'An open marketplace for independent digital creators with a focus on independent video games.', categories: ['gaming-interactive','indie-games'], tags: ['indie','games','marketplace','creators','community'], content_type: 'community', quality_score: 93, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.gamedeveloper.com', title: 'Game Developer', description: 'The art, business, and technology of making games — postmortems, insights, and industry analysis.', categories: ['gaming-interactive','game-development'], tags: ['game-dev','postmortems','industry','design','programming'], content_type: 'blog', quality_score: 89, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://neal.fun', title: 'Neal.fun', description: 'Addictive interactive visualizations and games that make you think about big numbers and concepts.', categories: ['gaming-interactive','interactive-experiences'], tags: ['interactive','visualization','fun','educational','creative'], content_type: 'tool', quality_score: 95, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.theringer.com', title: 'The Ringer', description: "Bill Simmons' media company covering sports, pop culture, and technology with personality.", categories: ['sports-athletics','team-sports'], tags: ['sports','pop-culture','podcasts','analysis','nba'], content_type: 'blog', quality_score: 88, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://fivethirtyeight.com', title: 'FiveThirtyEight', description: "Nate Silver's data-driven analysis of politics, sports, science, and economics.", categories: ['sports-athletics','fantasy-sports-analytics'], tags: ['data','analytics','statistics','predictions','sports'], content_type: 'blog', quality_score: 91, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.outsideonline.com', title: 'Outside Magazine', description: 'The leading voice for active lifestyles — adventure, gear, health, and the great outdoors.', categories: ['sports-athletics','outdoor-adventure-sports'], tags: ['outdoors','adventure','gear','fitness','nature'], content_type: 'blog', quality_score: 87, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.mrmoneymustache.com', title: 'Mr. Money Mustache', description: 'The original financial independence blog — retire early through badassity and simple math.', categories: ['finance-money','personal-finance'], tags: ['fire','retirement','frugality','investing','independence'], content_type: 'blog', quality_score: 90, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.visualcapitalist.com', title: 'Visual Capitalist', description: "Making the world's information more accessible through data-driven visual content.", categories: ['finance-money','economics'], tags: ['infographics','data','economics','markets','visualization'], content_type: 'blog', quality_score: 89, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://finviz.com', title: 'Finviz', description: 'Free stock screener, heatmaps, and financial visualizations for market research.', categories: ['finance-money','investing'], tags: ['stocks','screener','heatmap','markets','analysis'], content_type: 'tool', quality_score: 88, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://ground.news', title: 'Ground News', description: 'Compare news coverage across the political spectrum — see how stories are covered differently.', categories: ['news-current-events','politics-policy'], tags: ['bias','comparison','media-literacy','politics','perspective'], content_type: 'tool', quality_score: 92, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://restofworld.org', title: 'Rest of World', description: "International nonprofit journalism covering technology's impact outside the Western bubble.", categories: ['news-current-events','world-affairs'], tags: ['global','technology','developing-world','journalism','international'], content_type: 'blog', quality_score: 93, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.mcsweeneys.net', title: "McSweeney's Internet Tendency", description: "Absurdist humor, literary satire, and the world's best open letters to people or entities unlikely to respond.", categories: ['humor-entertainment','comedy-satire'], tags: ['humor','satire','literary','absurdist','writing'], content_type: 'blog', quality_score: 90, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://tvtropes.org', title: 'TV Tropes', description: 'The all-devouring pop-culture wiki cataloging every narrative device and convention in storytelling.', categories: ['humor-entertainment','pop-culture'], tags: ['tropes','wiki','storytelling','media','analysis'], content_type: 'resource', quality_score: 89, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://pudding.cool', title: 'The Pudding', description: 'Visual essays explaining ideas debated in culture using data journalism and interactive graphics.', categories: ['humor-entertainment','reviews-criticism'], tags: ['data-journalism','visual-essays','interactive','culture','analysis'], content_type: 'blog', quality_score: 94, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.thedodo.com', title: 'The Dodo', description: 'The digital media brand for animal lovers — heartwarming stories of animals and the people who love them.', categories: ['pets-animals','dogs'], tags: ['animals','heartwarming','rescue','stories','video'], content_type: 'blog', quality_score: 85, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.nationalgeographic.com/animals', title: 'National Geographic Animals', description: 'The most comprehensive animal reference and wildlife conservation resource on the web.', categories: ['pets-animals','wildlife-conservation'], tags: ['wildlife','conservation','photography','education','species'], content_type: 'resource', quality_score: 93, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.scarymommy.com', title: 'Scary Mommy', description: 'Honest, unfiltered parenting stories and advice from real parents in the trenches.', categories: ['parenting-family','family-life'], tags: ['parenting','humor','honest','community','advice'], content_type: 'blog', quality_score: 86, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.khanacademy.org/kids', title: 'Khan Academy Kids', description: 'Free, joyful learning for children ages 2-8 with interactive activities and books.', categories: ['parenting-family','kids-activities-education'], tags: ['education','free','interactive','learning','children'], content_type: 'tool', quality_score: 94, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.electrek.co', title: 'Electrek', description: 'Leading the charge in electric vehicle news, reviews, and sustainable energy coverage.', categories: ['automotive-transport','electric-vehicles'], tags: ['electric-vehicles','tesla','sustainability','energy','news'], content_type: 'blog', quality_score: 88, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.thedrive.com', title: 'The Drive', description: "Auto news, reviews, and car culture with a voice — not your grandfather's automotive journalism.", categories: ['automotive-transport','cars-trucks'], tags: ['cars','reviews','culture','automotive','journalism'], content_type: 'blog', quality_score: 87, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://brilliant.org', title: 'Brilliant', description: 'Learn math, science, and computer science through guided, interactive problem solving.', categories: ['learning-knowledge','online-courses'], tags: ['math','science','interactive','problem-solving','education'], content_type: 'tool', quality_score: 93, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://explorabl.es', title: 'Explorable Explanations', description: 'A hub for learning through play — interactive essays, simulations, and visualizations.', categories: ['learning-knowledge','tutorials-how-to'], tags: ['interactive','learning','simulations','visualizations','play'], content_type: 'resource', quality_score: 92, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://informationisbeautiful.net', title: 'Information is Beautiful', description: 'Making sense of the world through stunning data visualizations and infographics.', categories: ['learning-knowledge','data-visualization'], tags: ['infographics','data','visualization','design','clarity'], content_type: 'resource', quality_score: 91, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.theverge.com/features', title: 'The Verge Features', description: 'Award-winning longform technology journalism and deep-dive features.', categories: ['media-journalism','longform-writing'], tags: ['technology','longform','journalism','features','culture'], content_type: 'blog', quality_score: 90, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.densediscovery.com', title: 'Dense Discovery', description: 'A thoughtful weekly newsletter at the intersection of design, technology, and culture.', categories: ['media-journalism','newsletters'], tags: ['newsletter','design','technology','culture','curated'], content_type: 'blog', quality_score: 91, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.listennotes.com', title: 'Listen Notes', description: 'The best podcast search engine — discover podcasts across every topic and genre.', categories: ['media-journalism','podcasts'], tags: ['podcasts','search','discovery','directory','audio'], content_type: 'tool', quality_score: 88, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.levels.fyi/blog', title: 'Levels.fyi Blog', description: 'Data-driven career insights — compensation trends, negotiation tips, and tech industry analysis.', categories: ['career-professional','professional-development'], tags: ['career','compensation','negotiation','tech','data'], content_type: 'blog', quality_score: 87, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://remoteok.com', title: 'Remote OK', description: 'The largest remote job board with 50,000+ remote work positions across every field.', categories: ['career-professional','remote-work'], tags: ['remote','jobs','hiring','work-from-home','global'], content_type: 'tool', quality_score: 89, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.keyvalues.com', title: 'Key Values', description: 'Find engineering teams that share your values — filter companies by culture, not just perks.', categories: ['career-professional','communities-networking'], tags: ['culture','values','engineering','hiring','company-culture'], content_type: 'tool', quality_score: 90, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.openculture.com', title: 'Open Culture', description: 'The best free cultural and educational media on the web — courses, books, films, and more.', categories: ['learning-knowledge','culture-ideas'], tags: ['free','education','culture','books','courses'], content_type: 'resource', quality_score: 92, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.darksky.org', title: 'DarkSky International', description: 'Fighting light pollution to preserve the night sky for present and future generations.', categories: ['science-nature','climate-environment'], tags: ['light-pollution','astronomy','conservation','environment','activism'], content_type: 'resource', quality_score: 88, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.notion.so/templates', title: 'Notion Templates', description: 'Thousands of free templates for productivity, project management, and personal organization.', categories: ['technology','developer-tools'], tags: ['productivity','templates','organization','free','tools'], content_type: 'resource', quality_score: 87, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://css-tricks.com', title: 'CSS-Tricks', description: 'Daily articles about CSS, HTML, JavaScript, and all things related to web design and development.', categories: ['technology','design-creative'], tags: ['css','web-dev','tutorials','frontend','design'], content_type: 'blog', quality_score: 91, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.musicforprogramming.net', title: 'Music for Programming', description: 'A series of mixes designed to aid concentration and increase productivity while coding.', categories: ['arts-expression','technology'], tags: ['music','focus','programming','ambient','productivity'], content_type: 'resource', quality_score: 89, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.swyx.io', title: 'swyx.io', description: "Shawn Wang's essays on learning in public, developer experience, and the AI engineering stack.", categories: ['technology','career-professional'], tags: ['learning','developer-experience','ai','essays','career'], content_type: 'blog', quality_score: 89, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://www.futuretools.io', title: 'Future Tools', description: "A curated collection of the best AI tools, updated daily with reviews and categories.", categories: ['technology','ai-ml'], tags: ['ai-tools','directory','curated','reviews','productivity'], content_type: 'resource', quality_score: 88, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
  { url: 'https://lexfridman.com/podcast', title: 'Lex Fridman Podcast', description: 'Conversations about intelligence, consciousness, love, and power with scientists and thinkers.', categories: ['science-nature','culture-ideas'], tags: ['podcast','ai','science','philosophy','interviews'], content_type: 'resource', quality_score: 90, ai_content_likelihood: 'low', status: 'approved', source: 'manual' },
];

async function main() {
  console.log(`Inserting ${sites.length} seed sites...`);

  const now = new Date().toISOString();
  const rows = sites.map(s => ({ ...s, approved_at: now }));

  // Insert in batches of 20
  for (let i = 0; i < rows.length; i += 20) {
    const batch = rows.slice(i, i + 20);
    const { error } = await supabase.from('sites').upsert(batch, { onConflict: 'url' });
    if (error) {
      console.error(`Batch ${i / 20 + 1} failed:`, error.message);
    } else {
      console.log(`Batch ${i / 20 + 1}: inserted ${batch.length} sites`);
    }
  }

  // Verify
  const { count } = await supabase
    .from('sites')
    .select('*', { count: 'exact', head: true })
    .eq('status', 'approved');

  console.log(`\nTotal approved sites in database: ${count}`);
}

main().catch(err => {
  console.error('Fatal:', err);
  process.exit(1);
});
